"""cascase delete rule

Revision ID: 258d1572c84c
Revises: 8b5254f8fae0
Create Date: 2024-08-06 17:54:04.553208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258d1572c84c'
down_revision: Union[str, None] = '8b5254f8fae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('section_user_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'users', ['user_id'], ['id'])
    op.drop_constraint('spendings_section_id_fkey', 'spendings', type_='foreignkey')
    op.create_foreign_key(None, 'spendings', 'section', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spendings', type_='foreignkey')
    op.create_foreign_key('spendings_section_id_fkey', 'spendings', 'section', ['section_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key('section_user_id_fkey', 'section', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
