"""added lisst to soendings

Revision ID: 9bc231c3c2f7
Revises: dbb0581cd4cb
Create Date: 2024-07-20 19:11:51.431990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc231c3c2f7'
down_revision: Union[str, None] = 'dbb0581cd4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
