"""date fields

Revision ID: ac79efe967b4
Revises: 3f37b0f1013b
Create Date: 2024-07-18 13:35:09.835730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac79efe967b4'
down_revision: Union[str, None] = '3f37b0f1013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spendings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('spendings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spendings', 'updated_at')
    op.drop_column('spendings', 'created_at')
    # ### end Alembic commands ###
