"""added date and currency fields

Revision ID: bbb88b22f32b
Revises: a7d2cb8d3660
Create Date: 2024-07-20 17:50:03.418854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb88b22f32b'
down_revision: Union[str, None] = 'a7d2cb8d3660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spendings', sa.Column('data', sa.DateTime(), nullable=True))
    op.add_column('spendings', sa.Column('currency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spendings', 'currency')
    op.drop_column('spendings', 'data')
    # ### end Alembic commands ###
