"""fixed1

Revision ID: c426c3c56847
Revises: de848dbac951
Create Date: 2024-08-07 17:27:11.319234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c426c3c56847'
down_revision: Union[str, None] = 'de848dbac951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('images_section_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'section', ['section_id'], ['id'], ondelete='CASCADE')
    op.alter_column('section', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('section_user_id_fkey', 'section', type_='foreignkey')
    op.create_foreign_key(None, 'section', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('spendings', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('spendings_section_id_fkey', 'spendings', type_='foreignkey')
    op.create_foreign_key(None, 'spendings', 'section', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spendings', type_='foreignkey')
    op.create_foreign_key('spendings_section_id_fkey', 'spendings', 'section', ['section_id'], ['id'])
    op.alter_column('spendings', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'section', type_='foreignkey')
    op.create_foreign_key('section_user_id_fkey', 'section', 'users', ['user_id'], ['id'])
    op.alter_column('section', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_section_id_fkey', 'images', 'section', ['section_id'], ['id'])
    op.alter_column('images', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
