"""changes relation15

Revision ID: de848dbac951
Revises: 696cf8d0dd82
Create Date: 2024-08-07 17:13:39.814836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de848dbac951'
down_revision: Union[str, None] = '696cf8d0dd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('section', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('spendings', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('spendings_section_id_fkey', 'spendings', type_='foreignkey')
    op.create_foreign_key(None, 'spendings', 'section', ['section_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spendings', type_='foreignkey')
    op.create_foreign_key('spendings_section_id_fkey', 'spendings', 'section', ['section_id'], ['id'])
    op.alter_column('spendings', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('section', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('images', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
