"""changed types3

Revision ID: e1fae91e58ec
Revises: b8606b8da2c6
Create Date: 2024-07-18 12:49:09.169605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fae91e58ec'
down_revision: Union[str, None] = 'b8606b8da2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'sum',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('section', 'sum_currency',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('section', 'sum_currency',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('section', 'sum',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
